appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: g9Ur0QhRY88YmV/whMWSWCoMVLgUq/svXwQ8Q35CPY6ebHzpU7/EmCC7CMyreECoIpJ5ARue411iHRbUBcfmimA/w5BpS2j7LKX/Bp6LiBWPys9fZ+83pKWE9XZCxgDMazYgW9VocNB4Zl3xEHSZ8FRatRRF8c3YeJo7pvQtQSZVlp9IOt0zdGXz1ryNTlIBQ6gwXQKyT2zMGU0rgFjPaUfxbOM7tVSaoYQT4M5+UERADTXD3z4x1rOrMC7+MuPF9vBfbmIu1ue0c0Cg60M+ieAW9CJXlMCR+JXMhmkcnwZMY3BcPnkAe42SlZ3SJj/+JKX4GmJM4LiS2u1z+Y+RwaG4amgU0U47YB/kJTKfJTy+yDkqo/oQ2DMvJyHM8ZXQrXZa73llvhvN+qubcv1D9RzzXWVnia0PzSPUkonakzfRt+4rJfoB38LPi/b8URF8gFI9t+V/4dDr0laaHAmdOabKzRtLF3KoKC1Q+TaF01ws7CFnYGl9h/m72xULDCQzyEfOUhUsKcFuBwp8x3IbZLGHQBUWLfmuI2kffb6LbH+d8T31qIWTB0zFk82hf1HfmaGSTYlgEaONUauHTieX7utO55M4hVC4eY0d5N9NosU2RgiCdqtUnUk1pnA5DjEwbk+H9UhdR7a68n7WtGOYBPKDqjqc5iGNmpvexeO1NcU=}
